name: Publish docs on GH Pages
on:
  workflow_call:
  workflow_dispatch:

jobs:
  gen-and-public:
    runs-on: ubuntu-22.04
    steps:

     - uses: actions/checkout@v4.1.1
       with:
        fetch-depth: 0

     - name: Generate API documentation
       if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
       run: |
         VERSION=$(git tag --sort=committerdate | tail -1)
         echo Generating API documentation for version $VERSION
         ./gradlew -Pversion=$VERSION dokkaHtml

     - uses: JamesIves/github-pages-deploy-action@v4
       name: Publish API documentation
       if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
       with:
         branch: gh-pages
         folder: build/dokka/html
         target-folder: ./


